general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

#[keyboard]
#bindings = [
#{ key = "F11", action = "ToggleFullscreen" }
#]

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Semicolon", mods = "Alt", chars = "\u001b\u001b[D" },
  { key = "'", mods = "Alt", chars = "\u001b\u001b[C" }
]

